import { components, getCurrentContext, html, isResume } from "pawajs"
import { $state, runEffect,setContext,useContext,useInsert, RegisterComponent,useValidateComponent, useInnerContext } from "pawajs"
import {isServer} from 'pawajs/server.js'
import { useSupport } from "../express-init.js"
import { completeProgress, errorProgress, progress, simulateProgress, updateProgress } from "../progress.js"

/**
 * @type {Array<{name:string,group:Array<string>,routeNames:Array<string>,route:string}>}
 */
let routes=[]
export const setRoutes=(r)=>{
  routes=r
  RouterConfig(routes)
}
export const routeArray=[]
const route_entry=[]
export const routeMap=new Map()
export const intersetMap=new Map()


export const routeConfigs=()=>[routeArray,routeMap]
// console.log(routes)
/**
 * @typedef {{name:string,routeNames:Array<>,route:string,group:string}} RouteTypes
 */
/**
 * @param {Array<{route:string,next:Array<dRoutes>,group:string,load:()=>ImportNodeOptions}>} dRoutes
 * @param {{name:string,group:Array<string>,routeNames:Array<string>,route:string} | null} parentRoute
 */
const routeEntry=(dRoutes,parentRoute)=>{
    dRoutes.forEach((value) => {
        const path = value.path !== undefined ? value.path : (value.route || '')
        const children = value.children || value.next
        const component = value.component || value.load
        const configRoute={
            name:'',
            // Cleanly join paths and remove trailing slashes to prevent duplicate matches
            route: parentRoute 
                ? `${parentRoute.route === '/' ? '' : parentRoute.route}/${path}`.replace(/\/+$/, '') 
                : path.replace(/\/+$/, ''),
            routeNames:parentRoute?[...parentRoute?.routeNames] :[],
            notfound:'',
            // propagate render style from vite-plugin
            render: value.render,
            acceptQuery:value.inQuery,
            revalidate: value.revalidate,
            children:children || []
        }
        configRoute.route = configRoute.route.replace(/\/+/g, '/') || '/'
        if (component) {
          route_entry.push({
            route:configRoute.route,
            children:children || []
          })
        }

        // Trust the unique name generated by the Vite plugin, otherwise fall back to path or 'index'
        configRoute.name = value.name || (path.startsWith('/') ? path.slice(1) : path) || 'index'
        configRoute.notfound = value?.notfound ? configRoute.route : ''
        configRoute.routeNames.push(configRoute.name)
        if (Array.isArray(children)) {
            routeEntry(children,configRoute)
        }
        routeArray.push(configRoute)
        // Map all necessary loaders and metadata
        routeMap.set(configRoute.name, {
            name: configRoute.name,
            load: component,
            childViews: value.childViews || '',
            notfoundLoad: value.notfound,
            loadingLoad: value.loading,
            error: value.error
        })
    })
} 
/**@param {Array<{route:string,next:Array<dRoutes>,group:string}>} dRoutes */
export const RouterConfig=(dRoutes=[])=>{
    routeEntry(dRoutes)
}

export const RouteEntry=()=>{
  let page=routes
  let pages=''
  page.forEach(element => {
    if(!element.component) return
    pages+=`\n<route-view :path="'${element.path}'"></route-view>`
  });
  if (pages) {
    return pages
  }
  return '<div> route entry</div>'
}

export const matchRoute = (pattern, path) => {
  // Split and filter out empty strings to ignore leading/trailing/multiple slashes
  const patternParts = pattern.split('/').filter(Boolean);
  const pathParts = path.split('/').filter(Boolean);
    
  const params = {};
  
  for (let i = 0; i < patternParts.length; i++) {
    const part = patternParts[i];

    // Catch-all/Splat support: matches [:...slug] or [*slug]
    if (part.startsWith(':...') || part.startsWith('*')) {
      const paramName = part.startsWith('*') ? part.slice(1) : part.slice(4);
      const remainingValue = pathParts.slice(i).join('/');
      if (remainingValue) {
        params[paramName] = remainingValue;
        return [true, params];
      }
      return [false, {}];
    }

    if (pathParts[i] === undefined) return [false, {}];

    if (part.startsWith(':')) {
      params[part.slice(1)] = pathParts[i];
    } else if (part !== pathParts[i]) {
      return [false, {}];
    }
  }

  return [patternParts.length === pathParts.length, params];
};
export function enhanceHistoryAPI() {
    const originalPushState = history.pushState;
    const originalReplaceState = history.replaceState;
  
    const event = new Event('pushchange');
    const dispatchPushEvent = () => {
      window.dispatchEvent(event);
    };
    
    history.pushState = function (...args) {
      originalPushState.apply(this, args);
      dispatchPushEvent();
    };
  
    history.replaceState = function (...args) {
        originalReplaceState.apply(this, args);
        dispatchPushEvent();
      };
    window.addEventListener('popstate', () => {
        dispatchPushEvent()
      })
    }
    // console.log(routes);
    const count=$state(0)
    const actualRoute=$state('')
    
    // Lockout for navigation debounce
    let isNavigating = false;

   // In your RouterPlugin:
export const RouterPlugin = () => {
    return {
        attribute: {
            register: [
                {
                    fullName: 'route-link',
                    plugin: (el, attr) => {
                        const func = (e) => {
                            e.preventDefault()
                            e.stopPropagation()
                            
                            if (isNavigating) return;
                            isNavigating = true;
                            setTimeout(() => { isNavigating = false; }, 150);

                            const currentPath = window.location.pathname
                            const targetPath = new URL(el.href).pathname
                            
                            // Only push state if path actually changed
                            if (currentPath !== targetPath) {
                                history.pushState({}, '', el.href)
                                requestAnimationFrame(() => window.scrollTo({ top: 0 }));
                            } else {
                                // Same path, different hash - just scroll to element
                                const hash = new URL(el.href).hash
                                if (hash) {
                                    const element = document.querySelector(hash)
                                    if (element && attr.value === 'top') {
                                        element.scrollIntoView({ behavior: 'smooth' })
                                    }
                                }
                            }
                        }
                        const linkCurrent = () => {
                            return el.getAttribute('href') === actualRoute.value?.route
                        }
                        el._context['linkCurrent'] =linkCurrent
                        
                        if (el.tagName === 'A' && !isServer()) {
                            el.addEventListener('click', func)
                            el._setUnMount(() => {
                                el.removeEventListener('click', func)
                            })
                            el.setAttribute('rel', 'noopener')
                        }
                    }
                },
                {
                  fullName:'route-fetch',
                  mode:'client',
                  plugin:(el,attr)=>{
                    const {  prefetchManager } = useSupport()
                    const url=new URL(el.href).pathname
                    prefetchManager.prefetch(url)
                    
                  }
                }
            ]
        }
    }
}
let formerRouteNames=[]
export const routeContexts=setContext()
export const routeContext=setContext()
export const useRouter=()=>useContext(routeContext)
export const useRouteState=()=>useContext(routeContexts)
export const activePages={}
export const routeDataContext = setContext()


 // Progress state for loading bar
 export const prefetchControl=async(prefetchManager,route,parentFetches,init=true,url,flashMessage,errorRoute,loadingRoute)=>{
    let stopProgress
    if (!init) {
         stopProgress = simulateProgress(url, () => {
                    updateProgress(100, 'complete', url)
                })
                
                updateProgress(5, 'starting', url)
    }
   const prefetchPromise = prefetchManager.prefetch(route.value, parentFetches, {
                    onDownloadProgress: (p) => {

                        // Update progress with actual download progress
                        const actualProgress = Math.floor(p.progress * 100)
                        updateProgress(Math.max(actualProgress, progress.value.value), 'loading', url)
                    }
                })
                if (!init) {
                   Promise.resolve(prefetchPromise).then((result)=>{
                        if (result) {
                            if (result.success) {
                                document.title = result.metadata.title
                                  for (const key in data) {
                                  if (activePages[key]) {
                                    const updatePageData=activePages[key]
                                    const pageData=data[key]?.data || {}
                                    updatePageData.value={...pageData}
                                  }
                                  
                                }    
                                
                                // Complete progress
                                stopProgress()
                                updateProgress(100, 'complete', url)
                                completeProgress(url)
                            } else if(result.error){
                                  errorRoute.value = { ...errorRoute.value, [url]: true,message:result.error };
                            }
                            else {
                                
                                if (result.redirect) {
                                    if (result.message) {
                                        flashMessage.value = { 
                                            message: result.message, 
                                            type: result.type || 'info' 
                                        }
                                    }
                                    stopProgress()
                                    history.pushState({}, '', result.redirect)
                                    return
                                }
                                history.pushState({}, '', '/')
                            }
                        }
                    }).then(err =>{
                        errorRoute.value={...errorRoute.value,[url]:true,message:err}
                    })
                }
                return prefetchPromise
 }
export const useRouteData = () => useContext(routeDataContext)
const route=$state('')
export const loadingRoute=$state({})
export const errorRoute=$state({message:''})
export const Router=({children})=>{  
  const { clientRouting, prefetchManager , loadData, flashMessage,query} = useSupport()
  if(!isServer()){
  prefetchManager.setRouteArray(routeArray)
  }
  const isRoute=$state({
    param:{},
    routeNames:[],
    notfound:'',
    name:'',
    route:'',
    generalNotFound:false,
    fullUrl: '',
    keyUrl: '',
    shallow: false
  })
  if(routeArray.length === 0 && routes){
    RouterConfig(routes)
  }
  const loading=$state(false)
  if(isServer()){
        const {url}=useInnerContext()
        route.value = url === "" ?'/' : url        
    }else{
        route.value = window.location.pathname + window.location.search
    }
    const navigateTo = (url, options = {}) => {
  const {
    replace = false,
    state = {},
    scroll = true,
    shallow = false,
    query = null,
    hash = '',
  } = options;

  Promise.resolve().then(() => {
    let finalUrl = url;

    // Handle query merging
    if (query && typeof query === 'object') {
      const urlObj = new URL(url, window.location.origin);
      Object.entries(query).forEach(([key, value]) => {
        if (value === null || value === undefined) {
          urlObj.searchParams.delete(key);
        } else {
          urlObj.searchParams.set(key, value);
        }
      });
      finalUrl = urlObj.pathname + urlObj.search;
    }

    // Handle hash
    if (hash) {
      finalUrl += hash.startsWith('#') ? hash : `#${hash}`;
    }

    // Prevent unnecessary navigation
    const current = window.location.pathname + window.location.search + window.location.hash;
    if (current === finalUrl) return;

    const historyState = {
      ...state,
      shallow,
      timestamp: Date.now(),
    };

    if (replace) {
      history.replaceState(historyState, "", finalUrl);
    } else {
      history.pushState(historyState, "", finalUrl);
    }

    // Scroll behavior
    if (scroll) {
      requestAnimationFrame(() => {
        if (hash) {
          const el = document.querySelector(hash);
          if (el) {
            el.scrollIntoView({ behavior: "smooth" });
            return;
          }
        }
        window.scrollTo({ top: 0, behavior: "auto" });
      });
    }
  });
};
    let latest=''
    let enter=false
    let oldUrl=''
    const param=$state({})
    routeContext.setValue({current:()=>route.value,param,navigateTo})
    routeContexts.setValue({route,isRoute,loading,setLatest:(arg)=>latest=arg})

    const resolveRoute = (currentMatch) => {
    let extendRoute = []
    let parentFetches = false
    const newNames=[...currentMatch.routeNames]
    
    if (intersetMap.get(currentMatch.route)) {
      formerRouteNames.forEach((v)=>{
        newNames.push(v)
      })
      newNames.forEach(n => extendRoute.push(n))
        // Find common parent between old and new routes
        const commonParent = formerRouteNames.find(v => newNames.includes(v))
        if (!commonParent) return null
        
        // Keep old route segments that are being left behind
        formerRouteNames.forEach((n) => {
            if (!newNames.includes(n)) {
                extendRoute.push(n)
            }
        })
        
        // Only fetch parent if the common parent changed
        parentFetches = commonParent !== formerRouteNames[formerRouteNames.length - 1]
        
        // Update tracking
        formerRouteNames = newNames
        
    } else {
        // NORMAL NAVIGATION
        extendRoute = newNames || []
        
        // Find the first segment that's different
        let commonDepth = 0
        for (let i = 0; i < Math.min(formerRouteNames.length, newNames.length); i++) {
            if (formerRouteNames[i] === newNames[i]) {
                commonDepth++
            } else {
                break
            }
        }
        
        // Only fetch parent data if we're going to a different parent branch
        parentFetches = commonDepth < formerRouteNames.length - 1
        
        formerRouteNames = newNames
    }
    
    return { extendRoute, parentFetches }
}
    const handleNotFound = (path) => {
      const arraysOfRoute = path.split('/')
      arraysOfRoute.pop()
      const latestPath = arraysOfRoute.join('/')
      const newParams = {}

      // Use '/' if latestPath is empty to check for root-level 404 handlers
      const searchPath = latestPath === '' ? '/' : latestPath
      
      const matched = routeArray.filter(value => {
          const [match, param] = matchRoute(value.route, searchPath);
          if (param) Object.assign(newParams, param)
          return match
      })
      // console.log(matched,routes);
      
      matched.reverse()
      
      if (matched.length > 0 && matched[0].notfound) {
          isRoute.value = {
              routeNames: matched[0].routeNames || [],
              param: newParams,
              notfound: matched[0].notfound,
              route: '',
              name: matched[0].name,
              generalNotFound: true,
              fullUrl: path,
              keyUrl: path,
              shallow: false
          }
          param.value=newParams
      } else if (latestPath !== '') {
          // Continue searching up the path hierarchy
          handleNotFound(latestPath)
      } else {
          // Exhausted all paths, including root, so use the global fallback
          
          isRoute.value = {
              routeNames: [],
              param: newParams,
              notfound: '',
              name:'',
              route:'',
              generalNotFound: true,
              fullUrl: path,
              keyUrl: path,
              shallow: false
          }
          param.value=newParams
      }
    }

    const init=()=>{
      const oldUrlCopy=oldUrl
      oldUrl=route.value
      const url = new URL(route.value, isServer() ? 'http://localhost' : window.location.origin);
      const pathname = url.pathname;
      if (!isServer()) {
          const updateQuery = () => {
        const urlParams = new URLSearchParams(window.location.search)
        const queryObject = {}
        for (const [key, value] of urlParams.entries()) {
            queryObject[key] = value
        }
        query.value = queryObject
    }
    updateQuery()
      }

      const state = !isServer() ? (history.state || {}) : {};
      const isShallow = state.shallow || false;
      
      const newParams = {}
      
      const current = routeArray.filter((value) => {
        const [match,param]=  matchRoute(value.route, pathname);
        if(param){
          Object.assign(newParams,param)
        }
        return match
      })
      if(current.length > 1){
        // If multiple routes match (e.g., layout and index page for '/'),
        // prefer the more specific one (the one with more path segments in its name hierarchy).
        current.sort((a, b) => b.routeNames.length - a.routeNames.length);
      }  
      if (loadingRoute.value[latest]) {
        loadingRoute.value = { ...loadingRoute.value, [latest]: false };
      }
      if (errorRoute.value[latest]) {
        errorRoute.value = { ...errorRoute.value, [latest]: false,message:'' };
      }
      if(current.length > 0){
        
        latest=current[0].route
        actualRoute.value=current[0]
        const resolved = resolveRoute(current[0])
        if (!resolved) return

        const { extendRoute, parentFetches } = resolved
        
        if (isServer() || enter === false || isShallow) {
        const keyUrl = (isShallow && enter) ? isRoute.value.keyUrl : route.value;
        isRoute.value={
          routeNames:extendRoute,
          param:newParams,
          notfound:'',
          route:current[0].route,
          name:current[0].name,
          generalNotFound:false,
          fullUrl:  route.value,
          keyUrl: keyUrl,
          shallow: isShallow
        }
        param.value=newParams
        loadingRoute.value = { ...loadingRoute.value, [current[0].route]: false };
        }else{
          const url=latest
          
          loading.value=true  
           // Start progress simulation
                const stopProgress = simulateProgress(url, () => {
                    updateProgress(100, 'complete', url)
                })
                
                updateProgress(5, 'starting', url)
                
                loadingRoute.value = { ...loadingRoute.value, [current[0].route]: true };
                const prefetchPromise=prefetchControl(prefetchManager,route,parentFetches)                
                Promise.all([prefetchPromise])
                    .then(([result]) => {
                        if (result) {
                            if (result.success) {
                                document.title = result.metadata.title
                                // Complete progress
                                const data=result.data
                                
                                for (const key in data) {
                                  if (activePages[key]) {
                                    const updatePageData=activePages[key]
                                    const pageData=data[key]?.data || {}
                                    updatePageData.value={...pageData}
                                  }
                                  
                                }
                                stopProgress()
                                updateProgress(100, 'complete', url)
                                completeProgress(url)
                            } else if(result.error){
                                  errorRoute.value = { ...errorRoute.value, [current[0].route]: true,message:result.error };
                            }
                            else {
                                if (result.redirect) {
                                    if (result.message) {
                                        flashMessage.value = { 
                                            message: result.message, 
                                            type: result.type || 'info' 
                                        }
                                    }
                                    stopProgress()
                                    history.pushState({}, '', result.redirect)
                                    return
                                }
                                
                                
                                history.pushState({}, '', '/')
                            }
                        }
                        
                        isRoute.value = {
                            routeNames: extendRoute,
                            param: newParams,
                            notfound: '',
                            route: current[0].route,
                            name: current[0].name,
                            generalNotFound: false,
                            fullUrl: route.value,
                            keyUrl: route.value,
                            shallow: false
                        }
                        param.value=newParams
                        // Clear loading state for this route
                        loadingRoute.value = { ...loadingRoute.value, [current[0].route]: false };
                    })
                    .catch((e) => {
                        console.error('Route navigation error:', e)
                        errorRoute.value = { ...errorRoute.value, [current[0].route]: true,message:e };
                        stopProgress()
                        errorProgress(url)
                        flashMessage.value = {
                            message: e.message || 'Failed to load page',
                            type: 'error'
                        }
                    })
                    .finally(() => {
                      stopProgress()
                        loading.value = false
                    })      }
      enter=true
      }else{
        formerRouteNames=[]
        handleNotFound(route.value)
    }
  
  }
  if(isServer())init()
    
    runEffect(() => {
        if (isServer()) return;
        enhanceHistoryAPI();
        const pop = (e) => {
            const newPath = window.location.pathname + window.location.search
            const oldPath = route.value
            if (newPath !== oldPath) {
                route.value = newPath
            }
        }
        window.addEventListener('pushchange', pop);
        init();
        return () => {
            window.removeEventListener('pushchange', pop);
        }
    }, 0)
    runEffect(()=>{
      route.value = window.location.pathname + window.location.search
        return ()=>{
            init()   
        }
    },[route])
    if (children !== '') {
      const res=children.replace(/<route-entry><\/route-entry>/g,RouteEntry())
      return res
    }
    return html `
    <template>
        ${RouteEntry()}
    </template>
    `
}
